import 'package:azure_devops_sdk/api.dart';
import 'package:test/test.dart';

// tests for Avatar
void main() {
  var instance = Avatar();

  group('test Avatar', () {
    // bool isAutoGenerated (default value: null)
    test('to test the property `isAutoGenerated`', () async {
      // TODO
    });

    // String size (default value: null)
    test('to test the property `size`', () async {
      // TODO
    });

    // DateTime timeStamp (default value: null)
    test('to test the property `timeStamp`', () async {
      // TODO
    });

    // List<String> value (default value: [])
    test('to test the property `value`', () async {
      // TODO
    });


  });

}
